version: "3.8"
services:
  cassandra-db:
    container_name: "cassandra-db"
    image: "cassandra:4.1.3"
    ports:
      - "9042:9042"
    volumes:
      - "cassandra-db-data:/cassandra-db/data"
  mongo-db:
    container_name: "mongo-db"
    image: "mongo:6.0"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db-data:/mongo-db/data"
  py-spark:
    container_name: "py-spark"
    build: "./py-spark"
    depends_on:
      - "cassandra-db"
      - "mongo-db"
    volumes:
      - "./scripts:/py-spark/scripts"

volumes:
  cassandra-db-data:
    driver: local
  mongo-db-data:
    driver: local
